### ISSUE TITLE
No way to document query parameters on POST methods

### ISSUE THREAD

**Issue by renier** [tim-vandecasteele/grape-swagger#145]
I want to define an API like this:
```
POST /api/user?api_key=12345
{
username: "john"
email: "john@smith.com"
}
```

However, grape-swagger will assume that any parameters atop a POST method are either  "form" or "body" parameter types, so it will document them as such in the swagger json. This is fine in most cases, except the case above.

It seems there is [a way](https://github.com/tim-vandecasteele/grape-swagger/blob/master/lib/grape-swagger.rb#L255) to to specify some kind of `:param_type` key to override the behavior, but it is not clear how to use this, and Grape will treat such value as a validator (and complain the validator doesn't exist) if you try using it in a `params` block (e.g `requires :api_key, param_type: 'query'`).

So, what to do? I have only been able to work around this by shamefully monkey-patching `Grape::Validations::ParamsScope#validates` so that it does not treat `param_type` as a validator, and then the code linked above in _grape_swagger.rb_ can kick in.

Now, what do you guys recommend? Is this a valid issue? If so, should I submit something to the Grape guys instead? Or do we think there is a way to make that `param_type` work from grape-swagger?

Thanks!

**Comment by zsxking** [comment]
@dblock 
I figured out a work around to make param_type work:
```ruby
    class Base < Grape::API

      # Hacky fix to allow configuring param_type for parameters.
      class << self
        Grape::Route
        def fix_swagger_param_type()
          @combined_routes.each do |resource, routes|
            routes.each do |route|
              if route.route_params
                route.route_params.each do |param_name, param_attrs|
                  # grape-swagger is looking for param_type in route.route_params[<param_name>][:param_type]
                  # but Grape::Route only save :required, :type, :desc, :default, :values, :documentation
                  # so :documentation is the only hash it can get in.
                  # ideally, grape-swagger should look for [:documentation][:param_type] instead of [:param_type]
                  # But until that's fixed, this is a temporary fix.
                  if param_attrs.is_a?(Hash) && param_attrs.key?(:documentation) &&
                      param_attrs[:documentation].key?(:param_type)
                    param_attrs[:param_type] = param_attrs[:documentation][:param_type]
                  end
                end
              end
            end
          end
        end
      end

      add_swagger_documentation()
      fix_swagger_param_type()
    end

```
Then in params block I can do this:
```ruby

      desc 'Change application status'
      params do
        requires :action, type: Symbol, values: [:PAUSE, :RESUME, :STOP], documentation: {param_type: 'query'}
      end
      post :change do
        status 501
        {reason: params[:action]}
      end

```

**Comment by ruthearle** [comment]
@zsxking this solved my problem too. Thanks so much I spent almost one day on this (note to self: check the gem issues first!).

**Comment by dblock** [comment]
#225 fixes this, I am closing the issue, @zsxking correct me if I am wrong.
