### ISSUE TITLE
Cannot hide the documentation for specific blocks of api depending on user roles or other request dependent variables

### ISSUE THREAD

**Issue by DavidValin** [tim-vandecasteele/grape-swagger#164]
Hello

I'm trying to use grape-swagger + swagger ui to document my partially public api. I would like to show to anyone only the documentation for specific endpoints, not the whole api. So the roles of the current user (cookie or token param) will define which docs to show.

I know the "hidden" attribute in the "desc" block that accepts true / false. However, in these case, the value depends on something that should be determined at the time of the request.

I'm posting this as a issue since as it's not a bug, I think it should be something common also on you, am I right? Can someone post his experience dealing on these cases?

All the best

David Valín

**Comment by DavidValin** [comment]
Thanks dblock for your time!

**Comment by zbelzer** [comment]
Hack engage: https://github.com/tim-vandecasteele/grape-swagger/pull/214

**Comment by dblock** [comment]
I like your solution @zbelzer, lets clean it up and merge.
