### ISSUE TITLE
[Question] : `desc` taking a block vs a hash and what we should use

### ISSUE THREAD

**Issue by bradrobertson** [tim-vandecasteele/grape-swagger#165]
Just trying to sort out a discrepancy between *grape*, *grape-swagger* and the `desc` method.

Right now, the [grape docs](https://github.com/intridea/grape#describing-methods) say that desc takes a block and provides methods in that block for listing stuff out like headers etc. In the [grape swagger docs](https://github.com/tim-vandecasteele/grape-swagger#swagger-header-parameters) it ALSO says that desc takes a block, except that the example here actually passes it a hash.

Now, using the `desc` block style that grape expounds yields NO changes on the swagger docs (they seem to just be ignored), but using the hash style that the grape-swagger docs show in their example actually does work.

I'm just wondering... why is there a difference here? Ideally we'd be able to use grape as it is documented and not have to worry about what would work for grape-swagger. It's just incredibly confusing to know what style we should be using to properly generate docs.

**Comment by dblock** [comment]
I am going to close this in favor of a discussion in https://github.com/intridea/grape/issues/920.
