### ISSUE TITLE
Documenting API at namespace root

### ISSUE THREAD

**Issue by Beans0063** [tim-vandecasteele/grape-swagger#189]
APIs assigned to the root of a namespace seem to be missing from the generated swagger_doc.  For example, the api accessible at `http://localhost:3000/v1/mailer_templates` is missing when I view `http://localhost:3000/swagger_doc/mailer_templates`:

``` 
version 'v1', using: :path
resource :mailer_templates do
 desc "Return list of mailer templates"
 get do
  MailerTemplate.limit(20)
 end
end
```
Adding a url to route seems to fix this: 
```
get :list do
  MailerTemplate.limit(20)
end
```

The regex [here](
https://github.com/tim-vandecasteele/grape-swagger/blob/e977feac26d2ba125d92067e3f6a433738415131/lib/grape-swagger.rb#L20) seems to be excluding the root url.  Is this by design, if so how can route of `'/'` be included in swagger_docs?

Thanks

**Comment by Beans0063** [comment]
I couldn't reproduce my problem in specs, so perhaps it's something specific to my app.  I was able to workaround the issue by changing from:

`version 'v1', using: :path` 

to the routing equivalent:

`prefix :v1`

With this change things are working correctly so I'll close out the issue.  Thanks for the help.

**Comment by tonycoco** [comment]
@Beans0063 & @dblock I had to dig for an hour for this... can we reopen this so it is surfaced as a bug and fixed?

**Comment by dblock** [comment]
@tonycoco Is this any different from https://github.com/tim-vandecasteele/grape-swagger/issues/192?

**Comment by tonycoco** [comment]
Nope, @dblock, I referenced that after I found that issue too

**Comment by dblock** [comment]
Resolved in https://github.com/tim-vandecasteele/grape-swagger/pull/216.
