### ISSUE TITLE
Fail to show some operations when api version is part of path

### ISSUE THREAD

**Issue by carelvwyk** [tim-vandecasteele/grape-swagger#192]
In Grape, if the api version is part of the path ( `version 'v1', using: :path` ), the grape-swagger route_match regex fails to match all paths.
To reproduce, add the following line to  grape-swagger/example/api.rb below `format :json` (line 7): `version 'v1', using: :path`

In this case, grape generates routes with paths that looks as follows: `/:version/invoices`
Which is not properly matched by the regex in grape-swagger/lib/grape-swagger.rb line 23 (`route_match = route_match.match('\/([\w|-]*?)[\.\/\(]') || route_match.match('\/([\w|-]*)')`)

**Comment by dblock** [comment]
This looks legit, would you please write a spec for this?

**Comment by carelvwyk** [comment]
Ok, will do later today or tomorrow

**Comment by minch** [comment]
I haven't had time to write a spec yet, will send a pr once I do, but I had the same problem and here's a *potential* fix:

https://github.com/minch/grape-swagger/commit/ae9e833b4629985d7debb83bd755957bde95a419

I say "potential" as I haven't written any specs or checked to see if this breaks anything else.

The issue, for me at least, is that the second regex doesn't match index routes when the format is not in the route (as it's been explicitly declared in the given resource, e.g., `format :json`).

Temporary workaround would also be to allow other formats, and use `default_format`.

**Comment by dblock** [comment]
Thanks @minch, looking forward to it.

**Comment by LuckyThirteen** [comment]
:+1:

**Comment by vincentjames501** [comment]
+1

**Comment by aceunreal** [comment]
:+1:

**Comment by calfzhou** [comment]
Facing the same issue.

When version is in url path, operations such as `get '/' do ... end` will not show.

**Comment by dblock** [comment]
Still accepting spec + PR for a fix! :)

**Comment by minch** [comment]
Lol, sorry guys I recently started a new job and have been crazy busy the past couple weeks.

I'll try to get a pr going soon..

**Comment by ahmeij** [comment]
Just to confirm, the fix seems to work I see the missing endpoints again after hacking the method as indicated above. I'll try to produce a failing spec.

**Comment by tonycoco** [comment]
Additional information here: #189

**Comment by dm1try** [comment]
I added the spec here https://github.com/tim-vandecasteele/grape-swagger/pull/216

**Comment by dblock** [comment]
Merged, see https://github.com/tim-vandecasteele/grape-swagger/pull/216.
