### ISSUE TITLE
NoMethodError - undefined method `settings' for API:Class

### ISSUE THREAD

**Issue by faisal-ali** [tim-vandecasteele/grape-swagger#193]
Solution to https://github.com/tim-vandecasteele/grape-swagger/issues/158

**Comment by faisal-ali** [comment]
t might sound stupid, but I was having the same issue, and all I did was swap [ gem 'grape' ] above [ gem 'grape-swagger' ] in Gemfile. It fixed the issue for me.

**Comment by dblock** [comment]
There should be a way to just `require 'grape'` somewhere and avoid this. Would love a repro case and lets fix this?

**Comment by u2** [comment]
@faisal-ali @dblock 
I have the some issue when I change  [ gem 'grape' ] after [ gem 'grape-swagger' ].
Just add ```require 'grape'```, all is ok.Hope it will help you.

**Comment by dblock** [comment]
Thanks, that works, merged #211.
