### ISSUE TITLE
While using grape-swagger it is imposible to use grape basic 'params' dsl

### ISSUE THREAD

**Issue by swistaczek** [tim-vandecasteele/grape-swagger#194]
Hello,
If I would like to take benefits from Swagger and declare some kind of relationship (eg. 1xN) using grape-entities (like example included in readme) it is imposible to combine this apporach with **params** method provided by base grape dsl. Please follow example below:

```ruby
desc 'Send multiple messages', params API::Entity::Message::Set.documentation
params do
  requires :messages, type: Array do
    requires :text, type: String
    optional :markdown, type: Boolean
  end
end
post do
  Messages.create(declared(params))
end
```

Issues:
* First of all this may be little not **DRY** due to repeated declaration of ```messages[][:markdown]``` type (```Boolean```) in params block and entity, but if you would like to leverage Grape type casting...
* **When params block used**: Grape-swaggers ignores :params in desc method and renders documentation based on definition inside ```params``` block
* **When :params specified only in ```desc``` options**: then it is not possible to use ```declared()``` helper (attributes whitelisting)

Desired state example:
```ruby
desc 'Send multiple messages', 
  params API::Entity::Message::Set.documentation

post do
  Messages.create(declared(params))
end
```

Currently I dont have much expertise with grape-swagger design but I would be glad to help.

**Comment by dblock** [comment]
I think this is at least partially related to https://github.com/intridea/grape/issues/827.

**Comment by swistaczek** [comment]
Yes, You are right @dblock :+1: .

**Comment by dblock** [comment]
@swistaczek Ok, so I think there will be nothing to do in this project once Grape supports the suggestions in https://github.com/intridea/grape/issues/827. I am going to close this.
