### ISSUE TITLE
Should "type" be picked up from the "using" option?

### ISSUE THREAD

**Issue by jhollinger** [tim-vandecasteele/grape-swagger#195]
Currently you have to specify both `using` and `type`, e.g. `expose :widget, using: Entities::Widget, documentation: {type: 'Widget'}`. Seems redundant. Is there any reason why `type` shouldn't be inferred from `using` when it's missing? I can't think of a reason but thought I'd ask first. If there are no objections I'll submit a PR.

**Comment by dblock** [comment]
Can you give a full endpoint example? I think this is just a subset of a much bigger issue.

**Comment by jhollinger** [comment]
So if I have an endpoint like this:

    class ApiV1::Entities::Category < Grape::Entity
      expose :name, documentation: {type: 'string', desc: 'Category name'}
    end

    class ApiV1::Entities::Widget < Grape::Entity
      expose :id, documentation: {type: 'integer', desc: 'Widget ID'}
      expose :name, documentation: {type: 'string', desc: 'Widget name'}
      # This is the important part
      expose :category, using: ApiV1::Entities::Category, documentation: {desc: 'Widget Category'}
    end
    ...
    get 'widgets/:id' do, http_codes: [[200, 'Ok', ApiV1::Entities::Widget]] do
      widget = Widget.find(params[:id])
      present widget, with: ApiV1::Entities::Widget
    end

The Swagger JSON response looks like this (note that "category" has a null `$ref`):

    ,"models": {
      "ApiV1::Widget":{"id":"ApiV1::Widget","properties":{"id":{"type":"integer","description":"Widget ID"},"name":{"type":"string","description":"Widget name"},"category":{"$ref":null,"description":"Widget Category"}}},
      "ApiV1::Category":{"id":"ApiV1::Category","properties":{"name":{"type":"string","description":"Category name"}}}}

![bad response model](https://cloud.githubusercontent.com/assets/81826/5778460/6dd4c13c-9d69-11e4-985f-cbf815ddf780.png)

**But** if I instead specify a type when exposing category:

      expose :category, using: ApiV1::Entities::Category, documentation: {type: 'ApiV1:Category', desc: 'Widget Category'}

I get the expected response:

    ,"models":{
      "ApiV1::Widget":{"id":"ApiV1::Widget","properties":{"id":{"type":"integer","description":"Widget ID"},"name":{"type":"string","description":"Widget name"},"category":{"$ref":"ApiV1::Category","description":"Widget Category"}}},
      "ApiV1::Category":{"id":"ApiV1::Category","properties":{"name":{"type":"string","description":"Category name"}}}}

![good response model](https://cloud.githubusercontent.com/assets/81826/5778578/4fcd3024-9d6a-11e4-9625-a5b6cb9939cf.png)

I think it would be reasonable for these two cases to behave the same way.

**Comment by dblock** [comment]
Yes, I agree.
