### ISSUE TITLE
Support Conditional Exposure when showing model schema

### ISSUE THREAD

**Issue by pablocrivella** [tim-vandecasteele/grape-swagger#201]
Is there a way to support [Conditional Exposure](https://github.com/intridea/grape-entity#conditional-exposure)?

**Comment by dm1try** [comment]
If I understood you correctly there is no way.

**Comment by pablocrivella** [comment]
Thanks @dm1try, i'll close this then.

**Comment by dblock** [comment]
If you want to describe what the feature would look like this can be reopened as a feature request.
