### ISSUE TITLE
Add path outside of grape to documentation

### ISSUE THREAD

**Issue by 23tux** [tim-vandecasteele/grape-swagger#202]
I have a path from doorkeeper `/oauth/token` which uses the client credentials flow to get an auth token. Basically, you post a `client_id` and a `client_secret` to the endpoint, and you get back a `token`, a `type` and a `expires_in` field.

It would be nice, to include this route inside the swagger documentation, so that my users could simply paste in their credentials, and get the auth token, without doing curl calls.

I'm not sure if this is possible, or if there is any workaround to include a route like this directly in grape and just redirect the request to the `/oauth/token` path.

**Comment by dblock** [comment]
This is a dup of https://github.com/tim-vandecasteele/grape-swagger/issues/188. 

A redirect will work, but for the purposes of documentation it seems silly. Ideally grape-swagger should be using a DSL that adds endpoints without any hacking, but it's a long way from there.
