### ISSUE TITLE
Support Range values

### ISSUE THREAD

**Issue by u2** [tim-vandecasteele/grape-swagger#203]
https://github.com/intridea/grape/pull/899

**Comment by dblock** [comment]
Yes, please contribute!

**Comment by u2** [comment]
#209

**Comment by u2** [comment]
Supplying a range to the :values option in grape v0.10.1, so maybe need to update grape version to v0.10.1 .

**Comment by dblock** [comment]
Closed via https://github.com/tim-vandecasteele/grape-swagger/pull/210.
