### ISSUE TITLE
Display possible param values

### ISSUE THREAD

**Issue by Machiaweliczny** [tim-vandecasteele/grape-swagger#204]
Is it possible to generate/display allowed param values. This is very important part of documentation when there're enumerable strings or only some values allowed and yet I can't find option supporting this. 

I mean when I use
```ruby
requires :scope, type: String, values: ['scopeX', 'scopeY']
```
I would like to see in swagger documentation that only these are valid. Now I can see only that String is allowed, but there's no support for values.

**Comment by dblock** [comment]
This would be useful, do you know if Swagger supports this (and how)?

**Comment by Machiaweliczny** [comment]
Hey I've just checked for it and swagger 2.0 does support this. 
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#user-content-parameter-object-
I'm thinking about *enum* property for my example, but there is also pattern, minimum, maximum, maxLength, minLength that are all worth supporting and I guess possible with grape.

**Comment by Machiaweliczny** [comment]
Sorry checked source and enum is supported in newest version.
