### ISSUE TITLE
How to define `notes` to an operation?

### ISSUE THREAD

**Issue by calfzhou** [tim-vandecasteele/grape-swagger#212]
i'm using grape 0.10.0 and grape-swagger 0.9.0.

As mentioned by [grape documentation](https://github.com/intridea/grape#describing-methods), i can add `detail` to each method, but the generated swagger doc doesn't contain information defined in `detail`. Swagger's operation `notes` filed is always an empty string.

I checked grape-swagger source code, the `notes` is generated by the following code:
```ruby
notes       = @@documentation_class.as_markdown(route.route_notes)
```
But i've no idea about what `route.route_notes` is.

**Comment by dblock** [comment]
Please see the README for how notes are used, there's a nice example, including how to do this in markdown.

**Comment by calfzhou** [comment]
Yes i read that, the problem is that the example only adds a `notes` to grape description, no other grape standard  fields. But i still need define a `success`, several `failure`s, i tried different ways but none of them works:

```ruby
desc 'Gets something', notes: 'details' do
  success AnEntity
end
```
Above will add `success` to doc but no `notes`.

```ruby
desc 'Gets something', notes: 'details', success: AnEntity
```
Above could generate `notes`, but no `success`.

```ruby
desc 'Gets something' do
  notes 'details'
  success AnEntity
end
```
Above will fail due to undefined method `notes`.

**Comment by calfzhou** [comment]
seems related to #165

**Comment by dblock** [comment]
Thanks @calfzhou for bringing this up. Lets talk about it in https://github.com/intridea/grape/issues/920. See my comments, I would take a PR that addresses those two issues described.

**Comment by dblock** [comment]
Reopening this since we basically lack support for notes given the new Grape DSL syntax with a block.
