### ISSUE TITLE
CORS Headers

### ISSUE THREAD

**Issue by fl00r** [tim-vandecasteele/grape-swagger#218]
Hi!

https://github.com/tim-vandecasteele/grape-swagger/blob/c9fb720bc9e191dd4faa47237425a33edb899552/lib/grape-swagger.rb#L394

Setting CORS header implicitly is not the best idea.
1) User could want to set CORS by himself in his favorite server (nginx/apache). In this case client (browser) will get this headers twice what will lead to an error.
2) Wildcard is not fully supported, so if you want to use cookies it won't work at all.
3) It is hard to debug, what piece of code in your Rails app leads to this bad side-effect: broken cors with doubled headers.

I believe such strange side-effects should be optional and turned off by default.

**Comment by dblock** [comment]
I agree. I'd like this to be refactored in favor of rack-cors.

**Comment by fl00r** [comment]
As I see you've fixed the issue. Thanks
