### ISSUE TITLE
When using the option format :json in Grape API

### ISSUE THREAD

**Issue by ristovskiv** [tim-vandecasteele/grape-swagger#224]
In some cases when I use the option from Grape "format :json" the api calls aren't shown in the swagger doc, and for some cases it works. For the example bellow it doesn't, can't figure it out what seems to be the problem.

```ruby
module Resources
  class Users::Index < Grape::API

    helpers APIHelpers

    resource :users do
      version 'v1', using: :path
      format :json

      before do
        authenticated_user
      end

      desc 'Fetch all users'
      get  do
        User.all
      end
    end
  end
end
```

**Comment by dblock** [comment]
Try writing a spec that reproduces the issue?

**Comment by dblock** [comment]
Closing this, there's no info that can be used here. Please reopen with errors/repro.
