### ISSUE TITLE
Array declaration is wrong

### ISSUE THREAD

**Issue by Fryie** [tim-vandecasteele/grape-swagger#237]
A param declaration like ```requires :foo, type: Array[Integer]``` generates a ```type: '[Integer]'``` entry in the JSON output.

However, the correct format would be:
```
type: 'array',
items: { type: 'integer' }
```
as [documented by the specification](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#433-data-type-fields) - this btw doesn't appear to have changed in Swagger 2.0.

See also [this issue](https://github.com/swagger-api/swagger-ui/issues/982).

It probably should also automatically append "[]" to the parameter name, although I'm not sure about that...

**Comment by dblock** [comment]
Check whether this is the case on HEAD and write a test that reproduces this? Thanks.

**Comment by Martin91** [comment]
I have meet the same issue. Can you resolve it? @Fryie

**Comment by Fryie** [comment]
Haven't had time to dig into it deeper, sorry. If you want, you can try to write a failing test as @dblock asked; otherwise I'll try to get to it as soon as I can manage.

**Comment by frodrigo** [comment]
Can be closed #237

**Comment by dblock** [comment]
Closed.
