### ISSUE TITLE
memory issues with large ranges

### ISSUE THREAD

**Issue by carlshimer** [tim-vandecasteele/grape-swagger#243]
I had an API definition that looked like:

requires :blahvalue, :type => Integer, values: 1262358112..3000000000, :desc => "foo"

This was designed to use a range to check to do basic validation. However, this blows up in the following code:

enum_values   = enum_values.to_a if enum_values && enum_values.is_a?(Range)

to_a expands the range completely into an array.  Which is very dangerous :)

**Comment by dblock** [comment]
This has been discussed and is definitely a problem, I'd appreciate a PR/fix.

**Comment by dblock** [comment]
Actually dup with https://github.com/tim-vandecasteele/grape-swagger/issues/235.
