### ISSUE TITLE
Version 0.10.1 not working with petstore ?

### ISSUE THREAD

**Issue by manny42** [tim-vandecasteele/grape-swagger#247]
I can't get my grape-swagger generated JSON to work with the [petstore] (http://petstore.swagger.io/) it generates an error saying `Uncaught TypeError: Cannot read property 'undefined' of undefined`

It keeps on displaying `fetching resource list: http://localhost:9292/swagger_doc` but never displays anything else.

The swagger doc generated seems to be fine as I can generate code using swagger-codegen.

Is there a know problem with this?

**Comment by dblock** [comment]
Does that URL work? - http://localhost:9292/swagger_doc

Check what you see in the JavaScript console in the browser.

**Comment by richardsondx** [comment]
I'm having the same issue

**Comment by richardsondx** [comment]
@dblock  did you figure this one out?

**Comment by dblock** [comment]
I didn't. Can someone do what I suggested above please?

**Comment by richardsondx** [comment]
@dblock  Here a temporary fix: I downloaded swagger on my local and  switch to an an older tag version `git checkout older_version_here`  and now its working again.

**Comment by dblock** [comment]
Well, the "fix" is nice, but if we have a bug I'd like to actually fix it. I don't have a repro, maybe you can help?

**Comment by richardsondx** [comment]
To reproduce the issue:

Create a rails app and add these gems to your Gemfile:
- gem 'grape'
- gem 'grape-swagger'

My gemlist shows the following dependencies and versions
grape (0.9.0)
grape-entity (0.4.4)
grape-kaminari (0.1.7)
grape-rails-cache (0.1.2)
grape-swagger (0.8.0)
grape-swagger-ui (0.0.9)

1) Then create a basic api using grape documentation.
2) start your rails server `rails s`  go to `http://petstore.swagger.io/` and enter the host `http://localhost:3000/swagger_doc`

And you'll see:
fetching resource list: http://localhost:3000/swagger_doc

And this in your browser console:
Uncaught TypeError: Cannot read property 'undefined' of undefined

**Comment by aitortomas** [comment]
I can reproduce the error when using grape-entity but not defining the entity in the description of the endpoint. It means instead of
`desc 'Statuses index', entity: API::Entities::Status`
you only define
`desc 'Statuses index'`
Besides that, when you add the entity, in my case, it renders an empty schema with `undefined`.
But that is probably an issue with swagger-ui.

**Comment by manny42** [comment]
When I retrieve `http://localhost:9292/swagger_doc` it works perfectly.

It does not show anything in the Javascript console.

My server is not a rails server, I built it over rake. And I don't use entities to display results.

Sorry for the late answer.

**Comment by DavidValin** [comment]
Im actually having the issue with grape-swagger 0.10.1 using swagger-ui 2.1.1-M2. The issue happens with the local swagger json endpoint. grape-swagger 0.10.1 uncompatible with swagger-ui 2.1.1-M2?

I'm using grape + ActiveRecord + rake.
```
Uncaught TypeError: Cannot read property 'undefined' of undefined
```

from line 4138 of swagger-ui.js:
```
4137:   Buffer.prototype.toString = function toString (encoding, start, end) {
4139:      var loweredCase = false
```

Can't figure out now

**Comment by dmitry** [comment]
I have the same issue. Looks like @DavidValin's solution should fix this issue.

**Comment by dm1try** [comment]
@dmitry is right, this one already fixed. use the lastest swagger-ui or [petstore](http://petstore.swagger.io/) )
can be closed.

**Comment by dblock** [comment]
OMG @dm1try vs. @dmitry серьёзно? :)

**Comment by dm1try** [comment]
omg @dblock знает русский? :) cool! 
буду иметь в виду

**Comment by dblock** [comment]
еше как :)

**Comment by dmitry** [comment]
Здесь орудует банда Дмитриев :squirrel:
