### ISSUE TITLE
Unable to get API methods from Grape modules

### ISSUE THREAD

**Issue by xurde** [tim-vandecasteele/grape-swagger#258]
This must be a very basic stuff and probably not a malfunctioning issue in the gem but I've spent hours trying to research and I haven't found anyone showing the same problem that I have in two different projects. Using: `grape (0.11.0)` and `grape-swagger (0.10.1)`

When I enable  the Swagger json listing I get this response listing endpoints but not the methods contained for each endpoint. See example:

```
{
  "apiVersion": "v0",
  "swaggerVersion": "1.2",
  "produces": [
    "application/json"
  ],
  "apis": [
    {
    "path": "/version.{format}",
    "description": "Operations about versions"
    },
    {
    "path": "/ping.{format}",
    "description": "Operations about pings"
    },
    {
    "path": "/users.{format}",
    "description": "Operations about users"
    },
    {
    "path": "/company.{format}",
    "description": "Operations about companies"
    },
    {
    "path": "/merchants.{format}",
    "description": "Operations about merchants"
    }
  ],
  "info": {}
}
```

I've also added CORS Allowance in config.ru like this:
```
require 'rack/cors'
use Rack::Cors do
  allow do
    origins '*'
    resource '*',
      headers: :any,
      methods: [:get, :post, :put, :delete, :options]
  end
end
```

Any clue on how to get methods for each endpoint listed inside?

Thanks in advance!

**Comment by dblock** [comment]
What is the layout of your API? This gem assumes that the first level is *it*, so this could be by design. What happens when you go into /merchants?

**Comment by xurde** [comment]
Sorry @dblock 
For some reason I was expecting a unified response in a nested file but I just figured out that swagger serves several paths (one per each endpoint).
So please, consider this as stupid assumption by my side, and the issue closed.

Thanks for the help!

**Comment by dblock** [comment]
There're no stupid assumptions! Glad this helped. If you think something is worth documenting, would welcome a PR.
