### ISSUE TITLE
hide_format not working with grape 0.12.0

### ISSUE THREAD

**Issue by Techbrunch** [tim-vandecasteele/grape-swagger#262]
```
gem 'grape', '0.12.0'
gem 'grape-swagger', '0.10.1'
gem 'grape-swagger-rails', :git => 'git://github.com/BrandyMint/grape-swagger-rails.git'
```

`.(format)`is added to the url even if `hide_format` is set to `true`.

**Comment by tmilewski** [comment]
I can confirm this behavior as well across two Grape APIs. `0.11.0` is fine while `0.12.0` isn't.

**Comment by dblock** [comment]
Looks like we need a spec/fix.

**Comment by DougHall** [comment]
Yep, verified. Thought I was going crazy.

**Comment by dblock** [comment]
Someone help with a fix? PR? Thanks!

**Comment by mattolson** [comment]
This appears to be the change in Grape that is causing issues: https://github.com/intridea/grape/pull/1001/files

**Comment by mattolson** [comment]
@dblock: https://github.com/tim-vandecasteele/grape-swagger/pull/273 fixes this

**Comment by mattolson** [comment]
cc @tim-vandecasteele @DougHall @tmilewski

**Comment by dblock** [comment]
Thanks everyone, lets cut a release soon. Try HEAD if you have a moment.
