### ISSUE TITLE
Endpoints with before blocks not generated

### ISSUE THREAD

**Issue by toshe** [tim-vandecasteele/grape-swagger#274]
Has anything major changed between 0.9.0 and 0.10.0?

I have several endpoints with the following `before` block defined:

```
before do
   authenticate!
end

get '/some_endpoint' do 
 {:hello => 'world'}
end
```

In 0.9.0 those endpoints used to show up in the swagger doc, now they're just marked as `not found`. 
I tried debugging but the routes just seem to vanish from `@combined_namespace_routes` when generating the docs.

**Comment by dblock** [comment]
Without digging in looks like a bug to me. Could use a repro/test.

**Comment by toshe** [comment]
yep, I'm on it

**Comment by toshe** [comment]
OK so I managed to reproduce the problem. It turns out that my Grape API Class had a prefix `api/v2` defined. Changing this to `version 'v2'` solved the problem.
So if you have a `Grape::API` class with a prefix `api` and you mount another `Grape::API` class inside with a prefix `api/v2` then it won't work

**Comment by dblock** [comment]
What does it generate? It still might be a bug, no? You should write a failing test like this and PR it.
